get http://localhost:5000/api/member/findAll/1/20
Content-Type: application/json
Authorization: Basic YWRtaW46c29mdHBvczIwMTM=
database: cGFua2hhbWhvbQ

###
get http://localhost:5000/api/member/client2
Content-Type: application/json
Authorization: Basic YWRtaW46c29mdHBvczIwMTM=
database: cGFua2hhbWhvbQ
